backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

# Cloudinary

media_library:
  name: cloudinary
  config:
    cloud_name: broeker
    api_key: 159818251742281


collections:
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string", default: "Anonymous" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: true # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Globals"
    name: "globals"
    files:
      - label: "Site Data"
        name: "site_data"
        delete: false
        file: "_data/site.json"
        fields:
          - {label: "Site name", name: "name", widget: "string"}
          - {label: "Site subtitle", name: "subtitle", widget: "string"}
          - {label: "Site emoji", name: "emoji", widget: "string"}
          - {label: "Site footer", name: "footer", widget: "string"}
          - {label: "Site Url", name: "url", widget: "string"}
          - 
          - {label: "Author Name", name: "authorName", widget: "string"}
          - {label: "Author Email Address", name: "authorEmail", widget: "string"}
          - {label: "Author Twitter Handle", name: "authorHandle", widget: "string", required: false}
          - {label: "Footer Short Description", name: "shortDesc", widget: "string"}
          - {label: "Maximum Posts Per Page", name: "maxPostsPerPage", widget: "number", default: 5}
          - {label: "Show Theme Credit", name: "showThemeCredit", widget: "boolean", default: true}
          - {label: "Enable Third Party Comments Area", name: "enableThirdPartyComments", widget: "boolean", default: false}
          - {label: "Payment Pointer (Web Monetization: https://bit.ly/2kTRI1b)", name: "paymentPointer", widget: "string"}
          - {label: "Favicon path (EG: /images/favicon.png)", name: "faviconPath", widget: "string"}
      - label: "Navigation"
        name: "nav"
        delete: false
        file: "_data/navigation.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
              - {label: "Is url to external site?", name: "external", widget: "boolean", required: false}
      - label: "Theme Settings"
        name: "theme"
        delete: false
        file: "_data/tokens.json"
        fields:
          - label: "Size Scale"
            name: "size-scale"
            widget: "object"
            fields: 
              - {label: "Base Size", name: "base", widget: "string", default: "1rem"}
              - {label: "Ratio: 300", name: "300", widget: "string", default: "0.8rem"}
              - {label: "Ratio: 500", name: "500", widget: "string", default: "1.25rem"}
              - {label: "Ratio: 600", name: "600", widget: "string", default: "1.56rem"}
              - {label: "Ratio: 700", name: "700", widget: "string", default: "1.95rem"}
              - {label: "Ratio: 800", name: "800", widget: "string", default: "2.44rem"}
              - {label: "Ratio: 900", name: "900", widget: "string", default: "3.05rem"}
              - {label: "Max Size", name: "max", widget: "string", default: "4rem"}
          - label: "Colors"
            name: "colors"
            widget: "object"
            fields: 
              - {label: "Primary", name: "primary", widget: "string", default: "hsl(208, 57%, 21%)"}
              - {label: "Primary Shade (darker)", name: "primary-shade", widget: "string", default: "hsl(208, 56%, 14%)"}
              - {label: "Primary Glare (lighter)", name: "primary-glare", widget: "string", default: "hsl(207, 57%, 31%)"}
              - {label: "Highlight", name: "highlight", widget: "string", default: "hsl(42, 98%, 77%)"}
              - {label: "Light", name: "light", widget: "string", default: "hsl(0, 0%, 100%)"}
              - {label: "Mid", name: "mid", widget: "string", default: "hsl(0, 0%, 80%)"}
              - {label: "Dark", name: "dark", widget: "string", default: "hsl(0, 0%, 20%)"}
              - {label: "Slate", name: "slate", widget: "string", default: "hsl(0, 0%, 25%)"}          